# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('url_logo', models.URLField(max_length=300)),
                ('url_bonus', models.URLField(max_length=300)),
                ('url_stock', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Banks')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('url_logo', models.URLField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='stocks',
            name='id_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Stores'),
        ),
        migrations.AddField(
            model_name='banks',
            name='partners',
            field=models.ManyToManyField(through='general.Stocks', to='general.Stores'),
        ),
    ]
